export enum UserPermissions {
    LOGIN = 'LOGIN',
    VIEW_USERS = 'VIEW_USERS',
    CREATE_USERS = 'CREATE_USERS',
    CREATE_ADMINS = 'CREATE_ADMINS',
    CREATE_ROLES = 'CREATE_ROLES',
    VIEW_COMPANY = 'VIEW_COMPANY',
    CREATE_COMPANY = 'CREATE_COMPANY'
}